var masterdict = {
  "754466": {
    "cultivation": "the process of preparing the land for growing crops",
    "the process of preparing the land for growing crops": "cultivation",
    "irrigation": "a means of supplying water for agriculture",
    "a means of supplying water for agriculture": "irrigation",
    "precipitation": "water that falls to the Earth’s surface",
    "water that falls to the Earth’s surface": "precipitation",
    "a famine": "severe hunger; a drastic food shortage",
    "severe hunger; a drastic food shortage": "a famine",
    "catastrophic": "extremely harmful",
    "extremely harmful": "catastrophic",
    "to abandon": "to leave, to give up",
    "to leave, to give up": "to abandon",
    "adversely": "affecting in a harmful, negative way",
    "affecting in a harmful, negative way": "adversely",
    "to anticipate": "to sense or expect something before it happens",
    "to sense or expect something before it happens": "to anticipate",
    "to aggregate": "to collect together into a whole",
    "to collect together into a whole": "to aggregate",
    "to fertilize": "to supply nourishment to plants",
    "to supply nourishment to plants": "to fertilize",
    "to intensify": "to increase in power or strength",
    "to increase in power or strength": "to intensify",
    "to obtain": "to gain possession of, to get",
    "to gain possession of, to get": "to obtain",
    "photosynthesis": "the process by which plants combine light energy into chemical energy",
    "the process by which plants combine light energy into chemical energy": "photosynthesis",
    "to collide": "to come together with great or violent force",
    "to come together with great or violent force": "to collide",
    "an eruption": "a sudden, often violent, outburst",
    "a sudden, often violent, outburst": "an eruption",
    "a flood": "an overflowing of water; an excessive amount",
    "an overflowing of water; an excessive amount": "a flood",
    "an impact": "a strong influence",
    "a strong influence": "an impact",
    "to persevere": "to keep going in spite of obstacles",
    "to keep going in spite of obstacles": "to persevere",
    "to plunge": "to go down suddenly",
    "to go down suddenly": "to plunge",
    "to unleash": "to release a thing or emotion",
    "to release a thing or emotion": "to unleash"
  },
  };
