var masterdict = {
    "63061": {
        "Minsk": "Belarus",
        "Belarus": "Minsk",
        "Brussels": "Belgium",
        "Belgium": "Brussels",
        "Kyiv": "Ukraine",
        "Ukraine": "Kyiv",
        "Bern": "Switzerland",
        "Switzerland": "Bern",
        "Astana": "Kazakhstan",
        "Kazakhstan": "Astana",
        "Paris": "France",
        "France": "Paris",
        "Skopje": "Macedonia",
        "Macedonia": "Skopje",
        "Belgrade": "Serbia",
        "Serbia": "Belgrade",
        "Budapest": "Hungary",
        "Hungary": "Budapest",
        "Prague": "Czech Republic",
        "Czech Republic": "Prague",
        "Baku": "Azerbaijan",
        "Azerbaijan": "Baku",
        "Valletta": "Malta",
        "Malta": "Valletta",
        "Madrid": "Spain",
        "Spain": "Madrid",
        "Warsaw": "Poland",
        "Poland": "Warsaw",
        "Berlin": "Germany",
        "Germany": "Berlin",
        "Stockholm": "Sweden",
        "Sweden": "Stockholm",
        "Bratislava": "Slovakia",
        "Slovakia": "Bratislava",
        "Podgorica": "Montenegro",
        "Montenegro": "Podgorica",
        "Athens": "Greece",
        "Greece": "Athens",
        "London": "United Kingdom",
        "United Kingdom": "London",
        "Amsterdam": "Netherlands",
        "Netherlands": "Amsterdam",
        "Vienna": "Austria",
        "Austria": "Vienna",
        "Sarajevo": "Bosnia and Herzegovina",
        "Bosnia and Herzegovina": "Sarajevo",
        "Yerevan": "Armenia",
        "Armenia": "Yerevan",
        "Monaco": "Monaco",
        "Nicosia": "Cyprus",
        "Cyprus": "Nicosia",
        "Luxembourg": "Luxembourg",
        "Oslo": "Norway",
        "Norway": "Oslo",
        "Ankara": "Turkey",
        "Turkey": "Ankara",
        "Dublin": "Republic of Ireland",
        "Republic of Ireland": "Dublin",
        "Tbilisi / Kutaisi*": "Georgia",
        "Georgia": "Tbilisi / Kutaisi*",
        "Andorra la Vella": "Andorra",
        "Andorra": "Andorra la Vella",
        "Chisinau": "Moldova",
        "Moldova": "Chisinau",
        "Bucharest": "Romania",
        "Romania": "Bucharest",
        "Copenhagen": "Denmark",
        "Denmark": "Copenhagen",
        "Helsinki": "Finland",
        "Finland": "Helsinki",
        "Zagreb": "Croatia",
        "Croatia": "Zagreb",
        "Moscow": "Russia",
        "Russia": "Moscow",
        "Reykjavík": "Iceland",
        "Iceland": "Reykjavík",
        "Ljubljana": "Slovenia",
        "Slovenia": "Ljubljana",
        "Sofia": "Bulgaria",
        "Bulgaria": "Sofia",
        "Vilnius": "Lithuania",
        "Lithuania": "Vilnius",
        "Lisbon": "Portugal",
        "Portugal": "Lisbon",
        "Vaduz": "Liechtenstein",
        "Liechtenstein": "Vaduz",
        "Tirana": "Albania",
        "Albania": "Tirana",
        "San Marino": "San Marino",
        "Tallinn": "Estonia",
        "Estonia": "Tallinn",
        "Riga": "Latvia",
        "Latvia": "Riga",
        "Rome": "Italy",
        "Italy": "Rome",
        "Vatican City": "Vatican City",
        "Tashkent": "Uzbekistan",
        "Uzbekistan": "Tashkent",
        "Manama": "Bahrain",
        "Bahrain": "Manama",
        "Doha": "Qatar",
        "Qatar": "Doha",
        "Ankara": "Turkey",
        "Turkey": "Ankara",
        "Vientiane": "Laos",
        "Laos": "Vientiane",
        "Beirut": "Lebanon",
        "Lebanon": "Beirut",
        "Abu Dhabi": "United Arab Emirates",
        "United Arab Emirates": "Abu Dhabi",
        "Ashgabat": "Turkmenistan",
        "Turkmenistan": "Ashgabat",
        "Riyadh": "Saudi Arabia",
        "Saudi Arabia": "Riyadh",
        "Tokyo": "Japan",
        "Japan": "Tokyo",
        "Kathmandu": "Nepal",
        "Nepal": "Kathmandu",
        "Sri Jayawardenapura / Colombo*": "Sri Lanka",
        "Sri Lanka": "Sri Jayawardenapura / Colombo*",
        "Nicosia": "Cyprus",
        "Cyprus": "Nicosia",
        "Islamabad": "Pakistan",
        "Pakistan": "Islamabad",
        "Damascus": "Syria",
        "Syria": "Damascus",
        "Beijing": "China",
        "China": "Beijing",
        "Amman": "Jordan",
        "Jordan": "Amman",
        "Naypyidaw": "Burma / Myanmar",
        "Burma / Myanmar": "Naypyidaw",
        "Baghdad": "Iraq",
        "Iraq": "Baghdad",
        "Dhaka": "Bangladesh",
        "Bangladesh": "Dhaka",
        "Tehran": "Iran",
        "Iran": "Tehran",
        "Manila": "Philippines",
        "Philippines": "Manila",
        "Seoul": "South Korea",
        "South Korea": "Seoul",
        "Jerusalem*": "Israel",
        "Israel": "Jerusalem*",
        "Thimphu": "Bhutan",
        "Bhutan": "Thimphu",
        "Kabul": "Afghanistan",
        "Afghanistan": "Kabul",
        "Tbilisi / Kutaisi*": "Georgia",
        "Georgia": "Tbilisi / Kutaisi*",
        "Bangkok": "Thailand",
        "Thailand": "Bangkok",
        "New Delhi": "India",
        "India": "New Delhi",
        "Moscow": "Russia",
        "Russia": "Moscow",
        "Astana": "Kazakhstan",
        "Kazakhstan": "Astana",
        "Ulaanbaatar": "Mongolia",
        "Mongolia": "Ulaanbaatar",
        "Yerevan": "Armenia",
        "Armenia": "Yerevan",
        "Kuala Lumpur": "Malaysia",
        "Malaysia": "Kuala Lumpur",
        "Kuwait City": "Kuwait",
        "Kuwait": "Kuwait City",
        "Sana'a": "Yemen",
        "Yemen": "Sana'a",
        "Pyongyang": "North Korea",
        "North Korea": "Pyongyang",
        "Bishkek": "Kyrgyzstan",
        "Kyrgyzstan": "Bishkek",
        "Dushanbe": "Tajikistan",
        "Tajikistan": "Dushanbe",
        "Malé": "Maldives",
        "Maldives": "Malé",
        "Singapore": "Singapore",
        "Jakarta": "Indonesia",
        "Indonesia": "Jakarta",
        "Bandar Seri Begawan": "Brunei",
        "Brunei": "Bandar Seri Begawan",
        "Hanoi": "Vietnam",
        "Vietnam": "Hanoi",
        "Baku": "Azerbaijan",
        "Azerbaijan": "Baku",
        "Phnom Penh": "Cambodia",
        "Cambodia": "Phnom Penh",
        "Muscat": "Oman",
        "Oman": "Muscat",
        "Dili": "Timor-Leste",
        "Timor-Leste": "Dili",
        "Jerusalem / Ramallah and Gaza*": "Palestine",
        "Palestine": "Jerusalem / Ramallah and Gaza*",
        "Quito": "Ecuador",
        "Ecuador": "Quito",
        "Lima": "Peru",
        "Peru": "Lima",
        "Managua": "Nicaragua",
        "Nicaragua": "Managua",
        "Sucre / La Paz*": "Bolivia",
        "Bolivia": "Sucre / La Paz*",
        "Port of Spain": "Trinidad and Tobago",
        "Trinidad and Tobago": "Port of Spain",
        "Mexico City": "Mexico",
        "Mexico": "Mexico City",
        "Ottawa": "Canada",
        "Canada": "Ottawa",
        "Kingstown": "Saint Vincent and the Grenadines",
        "Saint Vincent and the Grenadines": "Kingstown",
        "Montevideo": "Uruguay",
        "Uruguay": "Montevideo",
        "Bridgetown": "Barbados",
        "Barbados": "Bridgetown",
        "Belmopan": "Belize",
        "Belize": "Belmopan",
        "Saint George's": "Grenada",
        "Grenada": "Saint George's",
        "Georgetown": "Guyana",
        "Guyana": "Georgetown",
        "San José": "Costa Rica",
        "Costa Rica": "San José",
        "Santiago / Valparaíso*": "Chile",
        "Chile": "Santiago / Valparaíso*",
        "Nassau": "The Bahamas",
        "The Bahamas": "Nassau",
        "Castries": "Saint Lucia",
        "Saint Lucia": "Castries",
        "Tegucigalpa": "Honduras",
        "Honduras": "Tegucigalpa",
        "Kingston": "Jamaica",
        "Jamaica": "Kingston",
        "Guatemala City": "Guatemala",
        "Guatemala": "Guatemala City",
        "Port-au-Prince": "Haiti",
        "Haiti": "Port-au-Prince",
        "Basseterre": "Saint Kitts and Nevis",
        "Saint Kitts and Nevis": "Basseterre",
        "San Salvador": "El Salvador",
        "El Salvador": "San Salvador",
        "Caracas": "Venezuela",
        "Venezuela": "Caracas",
        "Brasília": "Brazil",
        "Brazil": "Brasília",
        "Saint John's": "Antigua and Barbuda",
        "Antigua and Barbuda": "Saint John's",
        "Asunción": "Paraguay",
        "Paraguay": "Asunción",
        "Bogotá": "Colombia",
        "Colombia": "Bogotá",
        "Washington D.C.": "United States",
        "United States": "Washington D.C.",
        "Buenos Aires": "Argentina",
        "Argentina": "Buenos Aires",
        "Paramaribo": "Suriname",
        "Suriname": "Paramaribo",
        "Roseau": "Dominica",
        "Dominica": "Roseau",
        "Havana": "Cuba",
        "Cuba": "Havana",
        "Panama City": "Panama",
        "Panama": "Panama City",
        "Santo Domingo": "Dominican Republic",
        "Dominican Republic": "Santo Domingo",
        "Canberra": "Australia",
        "Australia": "Canberra",
        "Majuro": "Marshall Islands",
        "Marshall Islands": "Majuro",
        "Wellington": "New Zealand",
        "New Zealand": "Wellington",
        "Port Moresby": "Papua New Guinea",
        "Papua New Guinea": "Port Moresby",
        "Honiara": "Solomon Islands",
        "Solomon Islands": "Honiara",
        "Palikir": "Federated States of Micronesia",
        "Federated States of Micronesia": "Palikir",
        "None / Yaren District": "Nauru",
        "Nauru": "None / Yaren District",
        "Port Vila": "Vanuatu",
        "Vanuatu": "Port Vila",
        "Suva": "Fiji",
        "Fiji": "Suva",
        "Nuku'alofa": "Tonga",
        "Tonga": "Nuku'alofa",
        "Apia": "Samoa",
        "Samoa": "Apia",
        "Melekeok / Ngerulmud*": "Palau",
        "Palau": "Melekeok / Ngerulmud*",
        "Funafuti": "Tuvalu",
        "Tuvalu": "Funafuti",
        "Tarawa": "Kiribati",
        "Kiribati": "Tarawa",
        "Addis Ababa": "Ethiopia",
        "Ethiopia": "Addis Ababa",
        "Port Louis": "Mauritius",
        "Mauritius": "Port Louis",
        "Antananarivo": "Madagascar",
        "Madagascar": "Antananarivo",
        "Kampala": "Uganda",
        "Uganda": "Kampala",
        "Cairo": "Egypt",
        "Egypt": "Cairo",
        "Kinshasa": "Democratic Republic of the Congo",
        "Democratic Republic of the Congo": "Kinshasa",
        "Asmara": "Eritrea",
        "Eritrea": "Asmara",
        "Bangui": "Central African Republic",
        "Central African Republic": "Bangui",
        "Maseru": "Lesotho",
        "Lesotho": "Maseru",
        "Gaborone": "Botswana",
        "Botswana": "Gaborone",
        "Lusaka": "Zambia",
        "Zambia": "Lusaka",
        "Tunis": "Tunisia",
        "Tunisia": "Tunis",
        "Dodoma / Dar es Salaam*": "Tanzania",
        "Tanzania": "Dodoma / Dar es Salaam*",
        "Lomé": "Togo",
        "Togo": "Lomé",
        "São Tomé": "São Tomé and Príncipe",
        "São Tomé and Príncipe": "São Tomé",
        "Niamey": "Niger",
        "Niger": "Niamey",
        "Bamako": "Mali",
        "Mali": "Bamako",
        "Freetown": "Sierra Leone",
        "Sierra Leone": "Freetown",
        "Bujumbura": "Burundi",
        "Burundi": "Bujumbura",
        "Bissau": "Guinea-Bissau",
        "Guinea-Bissau": "Bissau",
        "Conakry": "Guinea",
        "Guinea": "Conakry",
        "Algiers": "Algeria",
        "Algeria": "Algiers",
        "Nouakchott": "Mauritania",
        "Mauritania": "Nouakchott",
        "Mbabane / Lobamba*": "Swaziland",
        "Swaziland": "Mbabane / Lobamba*",
        "Tripoli": "Libya",
        "Libya": "Tripoli",
        "Abuja": "Nigeria",
        "Nigeria": "Abuja",
        "Djibouti": "Djibouti",
        "Moroni": "Comoros",
        "Comoros": "Moroni",
        "Kigali": "Rwanda",
        "Rwanda": "Kigali",
        "Porto-Novo / Cotonou*": "Benin",
        "Benin": "Porto-Novo / Cotonou*",
        "Yaoundé": "Cameroon",
        "Cameroon": "Yaoundé",
        "Nairobi": "Kenya",
        "Kenya": "Nairobi",
        "N'Djamena": "Chad",
        "Chad": "N'Djamena",
        "Windhoek": "Namibia",
        "Namibia": "Windhoek",
        "Banjul": "The Gambia",
        "The Gambia": "Banjul",
        "Dakar": "Senegal",
        "Senegal": "Dakar",
        "Pretoria / Cape Town / Bloemfontein": "South Africa",
        "South Africa": "Pretoria / Cape Town / Bloemfontein",
        "Victoria": "Seychelles",
        "Seychelles": "Victoria",
        "Accra": "Ghana",
        "Ghana": "Accra",
        "Yamoussoukro / Abidjan*": "Côte d'Ivoire",
        "Côte d'Ivoire": "Yamoussoukro / Abidjan*",
        "Maputo": "Mozambique",
        "Mozambique": "Maputo",
        "Ouagadougou": "Burkina Faso",
        "Burkina Faso": "Ouagadougou",
        "Brazzaville": "Republic of the Congo",
        "Republic of the Congo": "Brazzaville",
        "Monrovia": "Liberia",
        "Liberia": "Monrovia",
        "Malabo": "Equatorial Guinea",
        "Equatorial Guinea": "Malabo",
        "Harare": "Zimbabwe",
        "Zimbabwe": "Harare",
        "Praia": "Cape Verde",
        "Cape Verde": "Praia",
        "Juba": "South Sudan",
        "South Sudan": "Juba",
        "Mogadishu": "Somalia",
        "Somalia": "Mogadishu",
        "Rabat": "Morocco",
        "Morocco": "Rabat",
        "Khartoum": "Sudan",
        "Sudan": "Khartoum",
        "Libreville": "Gabon",
        "Gabon": "Libreville",
        "Lilongwe": "Malawi",
        "Malawi": "Lilongwe",
        "Luanda": "Angola",
        "Angola": "Luanda",
    },
    "403879" : {
  "Cache memory": "This is a buffer of memory in the processor that is used to store copies of items that are most often fetched from the memory so that they can be fetched more quickly.",
  "This is a buffer of memory in the processor that is used to store copies of items that are most often fetched from the memory so that they can be fetched more quickly.": "Cache memory",
  "Flash memory": "A technology for storing data in an electronic format which is used for memory cards.",
  "A technology for storing data in an electronic format which is used for memory cards.": "Flash memory",
  "Multi-tasking": "A computer is multitasking if it appears to be running more than one program at the same time.",
  "A computer is multitasking if it appears to be running more than one program at the same time.": "Multi-tasking",
  "Primary memory": "Memory that can be addressed and accessed directly by the processor.",
  "Memory that can be addressed and accessed directly by the processor.": "Primary memory",
  "Random Access Memory (RAM)": "Memory that is used to store the programs and data currently in use by a computer. It is volatile which means that it gets erased when the computer is switched off.",
  "Memory that is used to store the programs and data currently in use by a computer. It is volatile which means that it gets erased when the computer is switched off.": "Random Access Memory (RAM)",
  "Read-Only Memory (ROM)": "Memory that is used to store programs permanently and in the same location such as the boot-up program. This memory is non-volatile and is not deleted when the computer is switched off.",
  "Memory that is used to store programs permanently and in the same location such as the boot-up program. This memory is non-volatile and is not deleted when the computer is switched off.": "Read-Only Memory (ROM)",
  "Virtual memory": "This is an area of the hard disk that is used to store running programs as if it was RAM.",
  "This is an area of the hard disk that is used to store running programs as if it was RAM.": "Virtual memory",
  "Braille": "A technique that allows blind people to read by feeling a pattern of raised dots with their fingers.",
  "A technique that allows blind people to read by feeling a pattern of raised dots with their fingers.": "Braille",
  "Internal storage": "Storage that is built into the main computer unit.",
  "Storage that is built into the main computer unit.": "Internal storage",
  "Loading": "Moving a program or data from secondary storage to primary memory, so that it can be used by the processor.",
  "Moving a program or data from secondary storage to primary memory, so that it can be used by the processor.": "Loading",
  "Magnetic storage": "Storage that uses a surface which can be magnetised to store data.",
  "Storage that uses a surface which can be magnetised to store data.": "Magnetic storage",
  "Removable storage": "Storage that can be disconnected from the main computer unit, for example to transfer files between computers.",
  "Storage that can be disconnected from the main computer unit, for example to transfer files between computers.": "Removable storage",
  "Saving": "Moving a data, program or file from memory onto secondary storage for later use.",
  "Moving a data, program or file from memory onto secondary storage for later use.": "Saving",
  "Secondary storage device": "A device that is used to store data when it is not in use, including after the computer has been switch off.",
  "A device that is used to store data when it is not in use, including after the computer has been switch off.": "Secondary storage device",
  "Solid state drive": "Storage that works by storing the data in electronic circuits.",
  "Storage that works by storing the data in electronic circuits.": "Solid state drive",
  "Braille keyboard": "An input device with a small number of keys that can be used to enter characters as a combination of these keys.",
  "An input device with a small number of keys that can be used to enter characters as a combination of these keys.": "Braille keyboard",
  "Braille printer": "An output device that produces Braille documents by impressing raised dots on a sheet of paper.",
  "An output device that produces Braille documents by impressing raised dots on a sheet of paper.": "Braille printer",
  "Digital camera": "An input device that makes electronic images or video clips.",
  "An input device that makes electronic images or video clips.": "Digital camera",
  "Eye tracker": "An input device that allows a user to control a computer by moving their eye, for example by working out what the user is looking at on a display.",
  "An input device that allows a user to control a computer by moving their eye, for example by working out what the user is looking at on a display.": "Eye tracker",
  "Ink-jet printer": "A type of printer that works by projecting tiny droplets of ink onto a sheet of paper.",
  "A type of printer that works by projecting tiny droplets of ink onto a sheet of paper.": "Ink-jet printer",
  "Input device": "A device that is used to enter data into a computer. It takes data that a user presents and converts it into binary code.",
  "A device that is used to enter data into a computer. It takes data that a user presents and converts it into binary code.": "Input device",
  "Joystick": "An input device, often used in games, that allows a user to move a pointer or a character by tilting a handle backwards, forwards, left or right.",
  "An input device, often used in games, that allows a user to move a pointer or a character by tilting a handle backwards, forwards, left or right.": "Joystick",
  "Keyboard": "An input device that consists of a set of keys that can be pressed by a user to enter characters into the computer system.",
  "An input device that consists of a set of keys that can be pressed by a user to enter characters into the computer system.": "Keyboard",
  "Laser printer": "A type of printer that works by using a laser to cause powdered ink to form the desired pattern on a sheet of paper.",
  "A type of printer that works by using a laser to cause powdered ink to form the desired pattern on a sheet of paper.": "Laser printer",
  "Microphone": "An input device that converts sound into an electrical signal which can be processed by a computer.",
  "An input device that converts sound into an electrical signal which can be processed by a computer.": "Microphone",
  "Monitor": "A screen used to display the output of a computer as a series of individual dots or pixels which can be updated as necessary.",
  "A screen used to display the output of a computer as a series of individual dots or pixels which can be updated as necessary.": "Monitor",
  "Mouse": "An input device that can be moved by a user to move a pointer on a screen. It has one or more buttons to allow the user to perform actions on the items on the screen.",
  "An input device that can be moved by a user to move a pointer on a screen. It has one or more buttons to allow the user to perform actions on the items on the screen.": "Mouse",
  "Multi touch monitor": "A touchscreen monitor capable of recognising several points of contact at the same time.",
  "A touchscreen monitor capable of recognising several points of contact at the same time.": "Multi touch monitor",
  "Optical Character Recognition (OCR)": "A technique for converting images of printed text into",
  "A technique for converting images of printed text into": "Optical Character Recognition (OCR)",
  "Output device": "A device that presents the result of processing. It converts binary data into a form which can be read by a user, or into binary data into a form which can be read by a user, or into a result in the external world.",
  "A device that presents the result of processing. It converts binary data into a form which can be read by a user, or into binary data into a form which can be read by a user, or into a result in the external world.": "Output device",
  "Plotter": "A type of printer that uses a mechanical ‘arm’ and a pen to make very precise drawings.",
  "A type of printer that uses a mechanical ‘arm’ and a pen to make very precise drawings.": "Plotter",
  "Printer": "An output device for producing hard copies of documents and images on paper.",
  "An output device for producing hard copies of documents and images on paper.": "Printer",
  "Refreshable Braille display": "An output device that has a row of mechanical dots which can be raised or lowered as required to make Braille characters.",
  "An output device that has a row of mechanical dots which can be raised or lowered as required to make Braille characters.": "Refreshable Braille display",
  "Scanner": "An input device that converts printed documents and images into a digital form.",
  "An input device that converts printed documents and images into a digital form.": "Scanner",
  "Speaker": "An output device that converts an electrical signal into sound.",
  "An output device that converts an electrical signal into sound.": "Speaker",
  "Speech recognition": "A technique that recognises a user’s speech and converts it into text.",
  "A technique that recognises a user’s speech and converts it into text.": "Speech recognition",
  "Speech synthesis": "A technique that converts text into speech.",
  "A technique that converts text into speech.": "Speech synthesis",
  "Touchpad": "An input device that is used to move a pointer on the screen by making similar movements across a flat surface.",
  "An input device that is used to move a pointer on the screen by making similar movements across a flat surface.": "Touchpad",
  "Touchscreen monitor": "An input/output device that allows a user to interact with the image displayed by touching it.",
  "An input/output device that allows a user to interact with the image displayed by touching it.": "Touchscreen monitor",
  "Tracker ball": "An input device that allows a user to move a pointer by moving a ball which is fixed in a socket.",
  "An input device that allows a user to move a pointer by moving a ball which is fixed in a socket.": "Tracker ball",
  "Webcam": "A digital camera that is used to capture images or, more usually, video, for transmitting immediately over the internet.",
  "A digital camera that is used to capture images or, more usually, video, for transmitting immediately over the internet.": "Webcam",
  "Boot program": "The program that is used to start the computer. It is automatically loaded so that its instructions can be fetched when the computer is turned on, and it eventually loads the operating system.",
  "The program that is used to start the computer. It is automatically loaded so that its instructions can be fetched when the computer is turned on, and it eventually loads the operating system.": "Boot program",
  "Central Processing Unit (CPU)": "The main component of the computer. It carries out all the processing by fetching and executing instructions.",
  "The main component of the computer. It carries out all the processing by fetching and executing instructions.": "Central Processing Unit (CPU)",
  "Clock speed": "The speed at which the processor carries out instructions, measured in Megahertz (MHz) or Gigahertz (GHz).",
  "The speed at which the processor carries out instructions, measured in Megahertz (MHz) or Gigahertz (GHz).": "Clock speed",
  "Core": "Each single processor circuit capable of fetching and executing instructions.",
  "Each single processor circuit capable of fetching and executing instructions.": "Core",
  "CPU cache": "Memory buffer on the processor that stores instructions which have been fetched before and allows them to be fetched more quickly the next time.",
  "Memory buffer on the processor that stores instructions which have been fetched before and allows them to be fetched more quickly the next time.": "CPU cache",
  "Fetch–Execute cycle": "The process by which programs are run on a computer. The processor repeatedly fetches the instructions of the program from memory and executes them.",
  "The process by which programs are run on a computer. The processor repeatedly fetches the instructions of the program from memory and executes them.": "Fetch–Execute cycle",
  "Multi-core processor": "A processor with more than one core (processor circuit) which means it can fetch and execute more than one instruction at a time.",
  "A processor with more than one core (processor circuit) which means it can fetch and execute more than one instruction at a time.": "Multi-core processor",
  "AND gate": "A logic gate that has two inputs. If both inputs are ‘1’ it will output ‘1’, otherwise it will output ‘0’.",
  "A logic gate that has two inputs. If both inputs are ‘1’ it will output ‘1’, otherwise it will output ‘0’.": "AND gate",
  "Binary digit": "The digits ‘0’ and ‘1’.",
  "The digits ‘0’ and ‘1’.": "Binary digit",
  "Binary number": "A number consisting only of binary digits.",
  "A number consisting only of binary digits.": "Binary number",
  "Denary number": "A number that uses the denary digits from 1 to 10.",
  "A number that uses the denary digits from 1 to 10.": "Denary number",
  "Digital circuit": "An electronic circuit based on binary numbers, where the presence or absence of electricity in any part of the circuit is represented by the digits ‘1’ and ‘0’.",
  "An electronic circuit based on binary numbers, where the presence or absence of electricity in any part of the circuit is represented by the digits ‘1’ and ‘0’.": "Digital circuit",
  "Logic gate": "A special circuit that allows a specific output depending on the inputs. A processor is made up of millions of these circuits.",
  "A special circuit that allows a specific output depending on the inputs. A processor is made up of millions of these circuits.": "Logic gate",
  "NOT gate": "A logic gate that has one input. If the input is ‘0’, its output is ‘1’. If the input is ‘1’, its output is ‘0’.",
  "A logic gate that has one input. If the input is ‘0’, its output is ‘1’. If the input is ‘1’, its output is ‘0’.": "NOT gate",
  "OR gate": "A logic gate that has two inputs. If either or both of the two inputs is ‘1’, its output is ‘1’.",
  "A logic gate that has two inputs. If either or both of the two inputs is ‘1’, its output is ‘1’.": "OR gate",
  "Binary": "Base 2 numbers. Only digits ‘1’ and ‘0’ are allowed.",
  "Base 2 numbers. Only digits ‘1’ and ‘0’ are allowed.": "Binary",
  "Bit": "The smallest unit of data – a bit can take the value of ‘0’or ‘1’, alternatively expressed as ‘false’ or ‘true’.",
  "The smallest unit of data – a bit can take the value of ‘0’or ‘1’, alternatively expressed as ‘false’ or ‘true’.": "Bit",
  "Byte": "The smallest addressable unit of data in a computer. Usually 8 bits.",
  "The smallest addressable unit of data in a computer. Usually 8 bits.": "Byte",
  "Gigabyte (GB)": "1024 megabytes",
  "1024 megabytes": "Gigabyte (GB)",
  "Kilobyte (kB)": "1024 bytes",
  "1024 bytes": "Kilobyte (kB)",
  "Megabyte (MB)": "1024 kilobytes",
  "1024 kilobytes": "Megabyte (MB)",
  "Nibble": "Half a byte",
  "Half a byte": "Nibble",
  "Terabyte (TB)": "1024 gigabytes",
  "1024 gigabytes": "Terabyte (TB)",
  "Binary": "Numbers expressed in base 2.",
  "Numbers expressed in base 2.": "Binary",
  "Decimal (denary)": "Numbers expressed in base 10.",
  "Numbers expressed in base 10.": "Decimal (denary)",
  "Hexadecimal": "Numbers expressed in base 16.",
  "Numbers expressed in base 16.": "Hexadecimal",
  "Overflow": "An error caused by attempting to store a number that is too large for the number of bits available.",
  "An error caused by attempting to store a number that is too large for the number of bits available.": "Overflow",
  "ASCII": "American Standard Code for Information Interchange – a7-bit character code.",
  "American Standard Code for Information Interchange – a7-bit character code.": "ASCII",
  "Character set": "The complete collection of characters that can been coded in a particular coding system.",
  "The complete collection of characters that can been coded in a particular coding system.": "Character set",
  "Unicode": "At least 16-bit code. Defines what characters it encodes and then uses a suitable number of octets to store them as a number.",
  "At least 16-bit code. Defines what characters it encodes and then uses a suitable number of octets to store them as a number.": "Unicode",
  "Bit map": "An image file format where the picture is represented asset of dots or pixels.",
  "An image file format where the picture is represented asset of dots or pixels.": "Bit map",
  "Metadata": "Data about data.",
  "Data about data.": "Metadata",
  "Pixel": "’Picture cell’ – a dot that makes up a part of an image. Resolution The number of dots per unit length. It affects the clarity",
  "’Picture cell’ – a dot that makes up a part of an image. Resolution The number of dots per unit length. It affects the clarity": "Pixel",
  "Resolution": "The number of dots per unit length. It affects the clarity of the image.",
  "The number of dots per unit length. It affects the clarity of the image.": "Resolution",
  "Vector graphics": "Graphics stored as formulae.",
  "Graphics stored as formulae.": "Vector graphics",
  "Lossless compression": "A way of compressing a file without losing data.",
  "A way of compressing a file without losing data.": "Lossless compression",
  "Lossy compression": "A way of compressing a file by removing data.",
  "A way of compressing a file by removing data.": "Lossy compression",
  "Assignment": "Sets or resets the value stored in the storage location denoted by a variable name.",
  "Sets or resets the value stored in the storage location denoted by a variable name.": "Assignment",
  "Binary": "Base 2 arithmetic system using just 1s and 0s to store values.",
  "Base 2 arithmetic system using just 1s and 0s to store values.": "Binary",
  "Comparison": "Two data items are compared to produce a logical, TRUE or FALSE, output.",
  "Two data items are compared to produce a logical, TRUE or FALSE, output.": "Comparison",
  "Expression": "A combination of values, variables, operators and functions that are evaluated according to the rules of the language.",
  "A combination of values, variables, operators and functions that are evaluated according to the rules of the language.": "Expression",
  "Variable": "Name used to identify a value in memory that can change during the execution of the program.",
  "Name used to identify a value in memory that can change during the execution of the program.": "Variable",
  "Bit": "A Binary digIT, ‘0’ or ‘1’.",
  "A Binary digIT, ‘0’ or ‘1’.": "Bit",
  "Boolean": "Variables that store just two values, e.g. TRUE or FALSE.",
  "Variables that store just two values, e.g. TRUE or FALSE.": "Boolean",
  "Byte": "A group of binary (‘0’ or ‘1’) digits, usually 8 bits.",
  "A group of binary (‘0’ or ‘1’) digits, usually 8 bits.": "Byte",
  "Character": "Data type that stores a single character.",
  "Data type that stores a single character.": "Character",
  "Constant": "Name used to identify a value in memory that does not change during the execution of the program.",
  "Name used to identify a value in memory that does not change during the execution of the program.": "Constant",
  "DIV": "An arithmetic operator that returns the quotient after division.",
  "An arithmetic operator that returns the quotient after division.": "DIV",
  "Integer": "Whole number values, positive or negative.",
  "Whole number values, positive or negative.": "Integer",
  "MOD": "An arithmetic operator that returns the remainder after division.",
  "An arithmetic operator that returns the remainder after division.": "MOD",
  "Real": "Data type that will store decimal (or fractional) values.",
  "Data type that will store decimal (or fractional) values.": "Real",
  "String": "Data type used to store a string of characters.",
  "Data type used to store a string of characters.": "String",
  "Function": "A subroutine that executes the statements and returns a single value to the program.",
  "A subroutine that executes the statements and returns a single value to the program.": "Function",
  "Procedure": "A subroutine that executes the statements and returns control to the program.",
  "A subroutine that executes the statements and returns control to the program.": "Procedure",
  "Selection": "The pathway through a program is selected by using a condition to decide on what instructions to execute next.",
  "The pathway through a program is selected by using a condition to decide on what instructions to execute next.": "Selection",
  "Sequence": "Set of instructions to be carried out in the order they are written.",
  "Set of instructions to be carried out in the order they are written.": "Sequence",
  "Statement": "A single instruction or step within a program.",
  "A single instruction or step within a program.": "Statement",
  "Subroutine": "A subset of code within a larger program, which performs a specific task.",
  "A subset of code within a larger program, which performs a specific task.": "Subroutine",
  "Iteration": "A group of instructions is executed repeatedly until a condition is met (a loop).",
  "A group of instructions is executed repeatedly until a condition is met (a loop).": "Iteration",
  "Nesting": "When control structures are inserted within other control structures.",
  "When control structures are inserted within other control structures.": "Nesting",
  "Rogue value": "A value that will not occur as normal input and which is used to interrupt a process.",
  "A value that will not occur as normal input and which is used to interrupt a process.": "Rogue value",
  "Algorithm": "A set of rules specifying a how to solve a problem.",
  "A set of rules specifying a how to solve a problem.": "Algorithm",
  "Flowchart": "Diagram of the sequence of operations in a computer program.",
  "Diagram of the sequence of operations in a computer program.": "Flowchart",
  "Pseudocode": "A description of a computer programming algorithm that uses the structural conventions of a programming language, but is intended for human reading rather than machine reading.",
  "A description of a computer programming algorithm that uses the structural conventions of a programming language, but is intended for human reading rather than machine reading.": "Pseudocode",
  "Analogue": "A form of signal that can take any value between the lowest and the highest. Sound is like this.",
  "A form of signal that can take any value between the lowest and the highest. Sound is like this.": "Analogue",
  "Compression": "The process of reducing a file’s size by removing data.",
  "The process of reducing a file’s size by removing data.": "Compression",
  "Digital": "A form of signal that is either on or off. Computer music files must be digital.",
  "A form of signal that is either on or off. Computer music files must be digital.": "Digital",
  "MP3 MPEG-1 or MPEG-2": "P3 MPEG-1 or MPEG-2 Audio Layer III – a digital audio encoding format which uses lossy data compression. A common standard for digital music.",
  "P3 MPEG-1 or MPEG-2 Audio Layer III – a digital audio encoding format which uses lossy data compression. A common standard for digital music.": "MP3 MPEG-1 or MPEG-2",
  "Sampling": "The process of capturing data about the sound at intervals.",
  "The process of capturing data about the sound at intervals.": "Sampling",
  "Arithmetic operation": "A mathematical process that is performed on data.",
  "A mathematical process that is performed on data.": "Arithmetic operation",
  "Instruction set": "The total collection of instructions that a processor can carry out.",
  "The total collection of instructions that a processor can carry out.": "Instruction set",
  "Logical operation": "A comparison between two items of data.",
  "A comparison between two items of data.": "Logical operation",
  "Operand": "The part of an instruction that identifies the data to be handled by the operator.",
  "The part of an instruction that identifies the data to be handled by the operator.": "Operand",
  "Operator": "The part of an instruction that tells the processor what to do.",
  "The part of an instruction that tells the processor what to do.": "Operator",
  "Decision": "A selection from a range of options depending upon the result of a condition.",
  "A selection from a range of options depending upon the result of a condition.": "Decision",
  "Process": "To perform logical operations on (data) according to programmed instructions in order to achieve a desired result.",
  "To perform logical operations on (data) according to programmed instructions in order to achieve a desired result.": "Process",
  "Array": "A block of variables of the same type using a single name and an index value.",
  "A block of variables of the same type using a single name and an index value.": "Array",
  "Index": "An integer value that identifies and is used to locate a particular element within an array.",
  "An integer value that identifies and is used to locate a particular element within an array.": "Index",
  "ASCII": "American Standard Code for Information Interchange - A set of digital codes (numbers) widely used as a standard format for defining characters in a computer.",
  "American Standard Code for Information Interchange - A set of digital codes (numbers) widely used as a standard format for defining characters in a computer.": "ASCII",
  "Auto documentation": "A feature to note all the variables, modules, subroutines and comments as the project is developed. This is put into a text file that can be used during any maintenance of the program.",
  "A feature to note all the variables, modules, subroutines and comments as the project is developed. This is put into a text file that can be used during any maintenance of the program.": "Auto documentation",
  "Code editor": "A text editing area that helps to organise the code by managing the layout, including indenting structures and colour coding the command words, variables and comments so that they can be easily identified.",
  "A text editing area that helps to organise the code by managing the layout, including indenting structures and colour coding the command words, variables and comments so that they can be easily identified.": "Code editor",
  "Debugger": "Utility within an IDE that identifies errors in the code and suggests possible fixes.",
  "Utility within an IDE that identifies errors in the code and suggests possible fixes.": "Debugger",
  "Error diagnostics": "Error warnings to identify any problems in the code.",
  "Error warnings to identify any problems in the code.": "Error diagnostics",
  "IDE": "IDE Integrated Development Environment containing various utilities used whilst writing computer code.",
  "IDE Integrated Development Environment containing various utilities used whilst writing computer code.": "IDE",
  "Run time environment": "Allows the developer to run the code during development to check for logical errors and that the code does what it is expected to do.",
  "Allows the developer to run the code during development to check for logical errors and that the code does what it is expected to do.": "Run time environment",
  "Syntax": "Set of rules that define the combinations of symbols that are acceptable in a computer language.",
  "Set of rules that define the combinations of symbols that are acceptable in a computer language.": "Syntax",
  "Erroneous": "Data that is not acceptable within the logic of a program, for example the wrong data type.",
  "Data that is not acceptable within the logic of a program, for example the wrong data type.": "Erroneous",
  "Extreme": "Data at the extreme end of the range for acceptable (valid) or unacceptable (invalid).",
  "Data at the extreme end of the range for acceptable (valid) or unacceptable (invalid).": "Extreme",
  "Logical error": "Error in the underlying logic of the program.",
  "Error in the underlying logic of the program.": "Logical error",
  "Valid": "Data that is acceptable within the logic of the program.",
  "Data that is acceptable within the logic of the program.": "Valid",
  "Binary code": "The code in which all data and instructions in a computer as stored. This is made of the digits 0 and 1.",
  "The code in which all data and instructions in a computer as stored. This is made of the digits 0 and 1.": "Binary code",
  "Communication device": "A device that allows a computer system to ‘talk’ to another system directly in binary code.",
  "A device that allows a computer system to ‘talk’ to another system directly in binary code.": "Communication device",
  "Computer Misuse Act -1990": "The UK law that makes it illegal to hack into a person’s computer and to disrupt deliberately someone else’s computer.",
  "The UK law that makes it illegal to hack into a person’s computer and to disrupt deliberately someone else’s computer.": "Computer Misuse Act -1990",
  "Computer system": "All the parts that make a computer work, including the hardware, software and data. This may not be a traditional computer.",
  "All the parts that make a computer work, including the hardware, software and data. This may not be a traditional computer.": "Computer system",
  "Data Protection Act -1998": "The UK law that tells organisations how they must protect the personal data of real people.",
  "The UK law that tells organisations how they must protect the personal data of real people.": "Data Protection Act -1998",
  "Electronic white board": "A computer system that uses a large white board as an input/output device in a classroom.",
  "A computer system that uses a large white board as an input/output device in a classroom.": "Electronic white board",
  "Environmental issues": "Issues concerned with whether something is good or bad for the environment.",
  "Issues concerned with whether something is good or bad for the environment.": "Environmental issues",
  "Ethical issues": "Issues concerned with whether something is morally right or wrong in itself.",
  "Issues concerned with whether something is morally right or wrong in itself.": "Ethical issues",
  "Input device": "A device that allows data to be entered into a computer by transforming it into an electronic form.",
  "A device that allows data to be entered into a computer by transforming it into an electronic form.": "Input device",
  "Output device": "A device that takes data which has been processed by the computer and translates it a human readable form.",
  "A device that takes data which has been processed by the computer and translates it a human readable form.": "Output device",
  "Storage device": "A device that stores data in a binary form for use later.",
  "A device that stores data in a binary form for use later.": "Storage device",
  "Virtual Learning Environment (VLE)": "A computer system that helps teachers by allowing them to provide learning resources to pupils and monitor their progress.",
  "A computer system that helps teachers by allowing them to provide learning resources to pupils and monitor their progress.": "Virtual Learning Environment (VLE)",
  "Adware": "A program that repeatedly and disruptively displays advertisements on a user’s computer.",
  "A program that repeatedly and disruptively displays advertisements on a user’s computer.": "Adware",
  "Anti-malware": "A utility that searches for and removes any malware on a computer.",
  "A utility that searches for and removes any malware on a computer.": "Anti-malware",
  "Antivirus": "A utility that searches for and removes any viruses on a computer.",
  "A utility that searches for and removes any viruses on a computer.": "Antivirus",
  "Custom-written software": "Software that is produced on commission, specifically fora user.",
  "Software that is produced on commission, specifically fora user.": "Custom-written software",
  "Device driver": "System software that is used by the operating system to control peripheral devices.",
  "System software that is used by the operating system to control peripheral devices.": "Device driver",
  "Disk formatting": "Initialising a disk for storage by identifying the data blocks on the disk and creating the file allocation table.",
  "Initialising a disk for storage by identifying the data blocks on the disk and creating the file allocation table.": "Disk formatting",
  "File allocation table": "An index of all the files that are stored on a disk and their allocation. It also keeps a record of free space on the disk.",
  "An index of all the files that are stored on a disk and their allocation. It also keeps a record of free space on the disk.": "File allocation table",
  "File management software": "Utilities that allow the user to perform common operations on files such as copying, deleting and moving.",
  "Utilities that allow the user to perform common operations on files such as copying, deleting and moving.": "File management software",
  "File transfer protocol (ftp)": "An agreed system and set of rules that allow different programs to transfer files across different computers over the internet.",
  "An agreed system and set of rules that allow different programs to transfer files across different computers over the internet.": "File transfer protocol (ftp)",
  "Firewall": "A utility or device that monitors the traffic between a computer and the internet and only allows connections that are authorised.",
  "A utility or device that monitors the traffic between a computer and the internet and only allows connections that are authorised.": "Firewall",
  "Malware": "Any program, such as viruses, worms, trojans and adware, that are designed to be harmful to the computer on which they are run.",
  "Any program, such as viruses, worms, trojans and adware, that are designed to be harmful to the computer on which they are run.": "Malware",
  "Memory management": "A function of the operating system that involves allocating memory to programs and data which are being used.",
  "A function of the operating system that involves allocating memory to programs and data which are being used.": "Memory management",
  "Multi-tasking": "A function of the operating system, where the processor is made to appear to perform several tasks at the same time by switching rapidly between the tasks.",
  "A function of the operating system, where the processor is made to appear to perform several tasks at the same time by switching rapidly between the tasks.": "Multi-tasking",
  "Conceptual view": "How the data is organised in a database.",
  "How the data is organised in a database.": "Conceptual view",
  "External view": "What the user sees of a database application.",
  "What the user sees of a database application.": "External view",
  "Flat-file database": "A database of only one table.",
  "A database of only one table.": "Flat-file database",
  "Hierarchical database": "A database organised on a tree structure.",
  "A database organised on a tree structure.": "Hierarchical database",
  "Physical view": "How the data is stored on the secondary storage.",
  "How the data is stored on the secondary storage.": "Physical view",
  "SQL": "QL Structured Query Language – a way to program queries to interrogate, maintain and set up a database.",
  "QL Structured Query Language – a way to program queries to interrogate, maintain and set up a database.": "SQL",
  "Client–server": "Network in which the server computers provide services for the client workstations.",
  "Network in which the server computers provide services for the client workstations.": "Client–server",
  "Hub": "Device that channels a number of input signals into one output line.",
  "Device that channels a number of input signals into one output line.": "Hub",
  "LAN": "Local area network",
  "Local area network": "LAN",
  "NIC": "Network interface card/controller",
  "Network interface card/controller": "NIC",
  "Packet": "A unit of data sent on a packet switching network.",
  "A unit of data sent on a packet switching network.": "Packet",
  "Peer-to-peer": "Network in which all the computers are of equal status.",
  "Network in which all the computers are of equal status.": "Peer-to-peer",
  "Topology": "The layout of a network.",
  "The layout of a network.": "Topology",
  "WAN": "Wide area network",
  "Wide area network": "WAN",
  "ADSL": "Asymmetric digital subscriber line",
  "Asymmetric digital subscriber line": "ADSL",
  "Analogue signal": "Signal that can take any value between the lowest and the highest.",
  "Signal that can take any value between the lowest and the highest.": "Analogue signal",
  "Bandwidth": "The difference between the upper and lower frequencies in a set of carrier signals.",
  "The difference between the upper and lower frequencies in a set of carrier signals.": "Bandwidth",
  "Compression": "The processes of reducing the size of a file.",
  "The processes of reducing the size of a file.": "Compression",
  "Digital signal": "Signal that can take one of two values.",
  "Signal that can take one of two values.": "Digital signal",
  "Domain name": "Name assigned to a resource on the internet.",
  "Name assigned to a resource on the internet.": "Domain name",
  "HTML": "Hypertext Markup Language. The language used to define pages on the world wide web and similar networks.",
  "Hypertext Markup Language. The language used to define pages on the world wide web and similar networks.": "HTML",
  "Internet": "An international network of networks.",
  "An international network of networks.": "Internet",
  "IP address": "Internet protocol number: the unique number that identifies a resource on the internet.",
  "Internet protocol number: the unique number that identifies a resource on the internet.": "IP address",
  "Protocol": "Rules/standards for devices to communicate.",
  "Rules/standards for devices to communicate.": "Protocol",
  "Router": "A device that connects networks.",
  "A device that connects networks.": "Router",
  "TCP/IP": "Transmission control protocol/internet protocol",
  "Transmission control protocol/internet protocol": "TCP/IP",
  },
    "252166" : {
    "Infrared radiation": "Electromagnetic waves  between visible light and microwaves in the electromagnetic spectrum.",
    "Electromagnetic waves  between visible light and microwaves in the electromagnetic spectrum.": "Infrared radiation",
    "Emit": "Give out radiation.",
    "Give out radiation.": "Emit",
    "Emitter": "A substance that gives out radiation.",
    "A substance that gives out radiation.": "Emitter",
    "Absorber": "A substance that takes in radiation.",
    "A substance that takes in radiation.": "Absorber",
    "Reflector": "A substance that reflects radiation.",
    "A substance that reflects radiation.": "Reflector",
    "Conductor": "Material/object that conducts.",
    "Material/object that conducts.": "Conductor",
    "Insulator": "Material/object that is a poor conductor.",
    "Material/object that is a poor conductor.": "Insulator",
    "Free electrons": "Electron that moves about freely inside a metal and is not held inside an atom.",
    "Electron that moves about freely inside a metal and is not held inside an atom.": "Free electrons",
    "Diffuse": "Spreading out of particles away from each other.",
    "Spreading out of particles away from each other.": "Diffuse",
    "Convection currents": "The circular motion of matter caused by heating in fluids.",
    "The circular motion of matter caused by heating in fluids.": "Convection currents",
    "Fluid": "A liquid or a gas.",
    "A liquid or a gas.": "Fluid",
    "Density": "Mass per unit volume of a substance.",
    "Mass per unit volume of a substance.": "Density",
    "Evaporate": "Turn from liquid into a vapour.",
    "Turn from liquid into a vapour.": "Evaporate",
    "Condense": "Turn from vapour into a liquid.",
    "Turn from vapour into a liquid.": "Condense",
    "Temperature difference": "Differance in temperature between two points.",
    "Differance in temperature between two points.": "Temperature difference",
    "Mass": "The quantity of matter in an object; a measure of the difficulty of changing the motion of an object (in kilograms, kg)",
    "The quantity of matter in an object; a measure of the difficulty of changing the motion of an object (in kilograms, kg)": "Mass",
    "Energy transfer": "Movement of energy from one place to another or one form to another.",
    "Movement of energy from one place to another or one form to another.": "Energy transfer",
    "Specific heat capacity": "Energy needed by 1kg of the substance to raise its temperature by 1 degree C.",
    "Energy needed by 1kg of the substance to raise its temperature by 1 degree C.": "Specific heat capacity",
    "Solar heating panel": "Sealed panel designed to use sunlight to heat water running through it.",
    "Sealed panel designed to use sunlight to heat water running through it.": "Solar heating panel",
    "payback time": "The time it takes to make savings that equal the total cost of installing an energy-saving measure such as double glazing.",
    "The time it takes to make savings that equal the total cost of installing an energy-saving measure such as double glazing.": "payback time",
    "Chemical energy": "energy in the form of chemical bonds within a substance",
    "energy in the form of chemical bonds within a substance": "Chemical energy",
    "kinetic energy": "the energy a moving object possesses",
    "the energy a moving object possesses": "kinetic energy",
    "gravitational potential energy": "the energy of an object due to its height above the ground.",
    "the energy of an object due to its height above the ground.": "gravitational potential energy",
    "Elastic potential energy": "the energy of an object under strain",
    "the energy of an object under strain": "Elastic potential energy",
    "electrical energy": "energy in the form of movement of electrons",
    "energy in the form of movement of electrons": "electrical energy",
    "Energy": "The ability to do work.",
    "The ability to do work.": "Energy",
    "conservation of energy": "the principle that energy can be neither created nor destroyed.",
    "the principle that energy can be neither created nor destroyed.": "conservation of energy",
    "useful energy": "energy transferred by a machine that is in a form that is needed",
    "energy transferred by a machine that is in a form that is needed": "useful energy",
    "wasted energy": "energy transferred by a machine that is not in a form that is needed",
    "energy transferred by a machine that is not in a form that is needed": "wasted energy",
    "Newtons (N)": "The unit of force.",
    "The unit of force.": "Newtons (N)",
    "Sankey Diagram": "A split arrow which shows the transfer of energy by a machine.",
    "A split arrow which shows the transfer of energy by a machine.": "Sankey Diagram",
    "Input energy": "energy supplied to a machine",
    "energy supplied to a machine": "Input energy",
    "efficiency": "the useful energy provided by a machine divided by the total energy multiplied by a hundred.",
    "the useful energy provided by a machine divided by the total energy multiplied by a hundred.": "efficiency",
    "electrical appliances": "A machine whose input energy is electrical. e.g. a kettle",
    "A machine whose input energy is electrical. e.g. a kettle": "electrical appliances",
    "Power": "energy transferred per time.",
    "energy transferred per time.": "Power",
    "Watt (W)": "1 joule / second",
    "1 joule / second": "Watt (W)",
    "kiloWatt (kW)": "1000 joules / second",
    "1000 joules / second": "kiloWatt (kW)",
    "P = ": "E/t",
    "E/t": "P = ",
    "E = ": "P x t",
    "P x t": "E = ",
    "kiloWatt-hour (kWh)": "The energy supplied to a 1kW appliance during 1 hour.",
    "The energy supplied to a 1kW appliance during 1 hour.": "kiloWatt-hour (kWh)",
    "total cost = ": "number of kWh used x cost per kWh",
    "number of kWh used x cost per kWh": "total cost = ",
    "payback time": "The time it takes to make savings that equal the total cost of installing an energy-saving measure such as double glazing.",
    "The time it takes to make savings that equal the total cost of installing an energy-saving measure such as double glazing.": "payback time",
    "Energy": "The ability to do work.",
    "The ability to do work.": "Energy",
    "Joules": "the unit of energy",
    "the unit of energy": "Joules",
    "turbine": "fan-like blades that rotate when a fluid passes over them",
    "fan-like blades that rotate when a fluid passes over them": "turbine",
    "generator": "an electromagnet which is free to rotate within coils of wire",
    "an electromagnet which is free to rotate within coils of wire": "generator",
    "biofuel": "fuel produced from biological waste",
    "fuel produced from biological waste": "biofuel",
    "renewable": "an energy resource which can be replenished",
    "an energy resource which can be replenished": "renewable",
    "atomic nucleus": "the centre of an atom, contains an immense amount of energy",
    "the centre of an atom, contains an immense amount of energy": "atomic nucleus",
    "nuclear fission": "the splitting of a large, unstable atom. This releases large amounts of energy.",
    "the splitting of a large, unstable atom. This releases large amounts of energy.": "nuclear fission",
    "tides": "the movement of large bodies of water such as the sea, it can be harnessed to generate electricity",
    "the movement of large bodies of water such as the sea, it can be harnessed to generate electricity": "tides",
    "non-renewable": "an energy resource which once consumed cannot be replaced",
    "an energy resource which once consumed cannot be replaced": "non-renewable",
    "solar cells": "Panels which when exposed to sunlight generate a potential difference.",
    "Panels which when exposed to sunlight generate a potential difference.": "solar cells",
    "geothermal energy": "thermal energy originally released from radioactive substances deep underground",
    "thermal energy originally released from radioactive substances deep underground": "geothermal energy",
    "acid rain": "rain water which contains dissolved sulfur dioxide. It can damage the environment.",
    "rain water which contains dissolved sulfur dioxide. It can damage the environment.": "acid rain",
    "Carbon Capture and Storage (CCS)": "capturing carbon from fossil fuel emissions and storing them underground, probably in old gas or crude oil fields.",
    "capturing carbon from fossil fuel emissions and storing them underground, probably in old gas or crude oil fields.": "Carbon Capture and Storage (CCS)",
    "National grid": "a network of powerstations, transformers, businesses and homes that transports electricity from where it is generated to where it is needed.",
    "a network of powerstations, transformers, businesses and homes that transports electricity from where it is generated to where it is needed.": "National grid",
    "Transformers": "machines which either increase or decrease the voltage, without losing energy.",
    "machines which either increase or decrease the voltage, without losing energy.": "Transformers",
    "step-up transformer": "machine which increases voltage",
    "machine which increases voltage": "step-up transformer",
    "step-up transformer use": "allows the transportation of electrical energy with less energy loss.",
    "allows the transportation of electrical energy with less energy loss.": "step-up transformer use",
    "step-down transformer": "Machine which decreases voltage",
    "Machine which decreases voltage": "step-down transformer",
    "step-down transformer use": "allows the use of electrical energy in the home, safely",
    "allows the use of electrical energy in the home, safely": "step-down transformer use",
    "230V": "the mains voltage in the UK",
    "the mains voltage in the UK": "230V",
    "start-up time": "the time it takes for a power station to be built and for it to produce electricity",
    "the time it takes for a power station to be built and for it to produce electricity": "start-up time",
    "base load": "the average demand for electricity across the country",
    "the average demand for electricity across the country": "base load",
    "Mechanical waves": "Vibration that travels through a substance.",
    "Vibration that travels through a substance.": "Mechanical waves",
    "Electromagnetic wave": "Electric and magnetic disturbance that transfers energy from one place to another.",
    "Electric and magnetic disturbance that transfers energy from one place to another.": "Electromagnetic wave",
    "Vibrates": "Oscillate rapidly (or move to and fro rapidly about a certain position).",
    "Oscillate rapidly (or move to and fro rapidly about a certain position).": "Vibrates",
    "Oscillates": "Move to and fro about a certain position along a line.",
    "Move to and fro about a certain position along a line.": "Oscillates",
    "Perpendicular": "At right angles.",
    "At right angles.": "Perpendicular",
    "Transverse wave": "Wave in which the vibrations are perpendicular to the direction of the energy transfer.",
    "Wave in which the vibrations are perpendicular to the direction of the energy transfer.": "Transverse wave",
    "Longitudinal wave": "Wave in which the vibrations are  parallel to the direction of energy transfer.",
    "Wave in which the vibrations are  parallel to the direction of energy transfer.": "Longitudinal wave",
    "Compressions": "Squeezed together.",
    "Squeezed together.": "Compressions",
    "Rarefaction": "Stretched apart.",
    "Stretched apart.": "Rarefaction",
    "Amplitude": "The height of a wave crest or a wave trough of a transverse wave from the rest position.",
    "The height of a wave crest or a wave trough of a transverse wave from the rest position.": "Amplitude",
    "Wavelength": "The distance from one wave crest to the next wave crest (along the waves).",
    "The distance from one wave crest to the next wave crest (along the waves).": "Wavelength",
    "Frequency": "The number of wave crests passing a fixed point every second.",
    "The number of wave crests passing a fixed point every second.": "Frequency",
    "Speed": "Distance moved divided by time taken.",
    "Distance moved divided by time taken.": "Speed",
    "Plane Mirror": "A flat mirror.",
    "A flat mirror.": "Plane Mirror",
    "Normal": "Straight line through a surface or boundary perpendicular to the surface or boundary.",
    "Straight line through a surface or boundary perpendicular to the surface or boundary.": "Normal",
    "Angle of incidence": "Angle between the incidence ray and the normal.",
    "Angle between the incidence ray and the normal.": "Angle of incidence",
    "Angle of reflection": "Angle between the reflected ray and the normal.",
    "Angle between the reflected ray and the normal.": "Angle of reflection",
    "Virtual image": "An image formed where light rays appear to come from.",
    "An image formed where light rays appear to come from.": "Virtual image",
    "Real image": "An image formed where light rays meet.",
    "An image formed where light rays meet.": "Real image",
    "Refraction": "The change of direction of a light ray when it passes across a boundary between two transparent substances (including air).",
    "The change of direction of a light ray when it passes across a boundary between two transparent substances (including air).": "Refraction",
    "Boundary": "Line along which two substances meet.",
    "Line along which two substances meet.": "Boundary",
    "Diffraction": "The spreading of waves when they pass through a gap or around the edges of an obstacle which has a similar size as the wavelengh of the waves.",
    "The spreading of waves when they pass through a gap or around the edges of an obstacle which has a similar size as the wavelengh of the waves.": "Diffraction",
    "Ultrasound waves": "Sound wave at frequencies greater than 20 000Hz which is the upper frequency of the human ear.",
    "Sound wave at frequencies greater than 20 000Hz which is the upper frequency of the human ear.": "Ultrasound waves",
    "Echo": "Reflection of sound that can be heard.",
    "Reflection of sound that can be heard.": "Echo",
    "Pitch": "The pitch of a sound increases if the frequency of the sound waves increases.",
    "The pitch of a sound increases if the frequency of the sound waves increases.": "Pitch",
    "Resonate": "When sound vibrations build up in a musical instrument  and cause the sound from the instrument to become much louder.",
    "When sound vibrations build up in a musical instrument  and cause the sound from the instrument to become much louder.": "Resonate",
    "Electromagnetic spectrum": "A set of radiations that have differant wavelenths and frequencies but all travel at the same speed in a vacuum",
    "A set of radiations that have differant wavelenths and frequencies but all travel at the same speed in a vacuum": "Electromagnetic spectrum",
    "Wave speed": "Speed of travel of a wave.",
    "Speed of travel of a wave.": "Wave speed",
    "White light": "Light that consists of all the colours of the visible spectrum.",
    "Light that consists of all the colours of the visible spectrum.": "White light",
    "Optical fibres": "Thin glass fibre used to send light signals along.",
    "Thin glass fibre used to send light signals along.": "Optical fibres",
    "Band": "Part of the radio and microwave spectrum used for communications.",
    "Part of the radio and microwave spectrum used for communications.": "Band",
    "radio wave": "The longest wavelength of electromagnetic radiation.",
    "The longest wavelength of electromagnetic radiation.": "radio wave",
    "Microwave": "Electromagnetic radiation with a wavelength of 1-2cm. Used by mobile phones.",
    "Electromagnetic radiation with a wavelength of 1-2cm. Used by mobile phones.": "Microwave",
    "Visible light": "The part of the electromagnetic spectrum that can be detected by the human eye.",
    "The part of the electromagnetic spectrum that can be detected by the human eye.": "Visible light",
    "Doppler effect": "The change of wavelength (and frequency) of the waves from a moving source due to the motion of the source towards or away from the observer.",
    "The change of wavelength (and frequency) of the waves from a moving source due to the motion of the source towards or away from the observer.": "Doppler effect",
    "Ultraviolet Light": "The part of the EM spectrum with a slightly higher frequency than visible light, used in tanning booths and many birds can see this kind of light.",
    "The part of the EM spectrum with a slightly higher frequency than visible light, used in tanning booths and many birds can see this kind of light.": "Ultraviolet Light",
    "Cosmic microwave background radiation": "Electromagnetic radiation that has been travelling through space ever since it was created shortly after the big bang.",
    "Electromagnetic radiation that has been travelling through space ever since it was created shortly after the big bang.": "Cosmic microwave background radiation",
    "X-ray": "Very short wavelength EM radiation which can be used to produce images of bones. It is ionising.",
    "Very short wavelength EM radiation which can be used to produce images of bones. It is ionising.": "X-ray",
    "Big Bang theory": "The theory that the universe was created in a massive explosion and that the universe has been expanding ever since.",
    "The theory that the universe was created in a massive explosion and that the universe has been expanding ever since.": "Big Bang theory",
    "Gamma rays": "The shortest wavelength EM radiation which can be used to sterilise objects. It is ionising.",
    "The shortest wavelength EM radiation which can be used to sterilise objects. It is ionising.": "Gamma rays"
    },
    "336097": {
    "8": "How many Bits are there in a Byte?",
    "28": "How many pieces make up a Domino set?",
    "42": "How many spots are there on a pair of dice?",
    "76": "Halleys Comet is visible from Earth in a cycle of how many years?",
    "206": "How many bones are there in the adult human body?",
    "1872": "In what year was the first FA Cup Final?",
    "1912": "In what year did the Titanic sink?",
    "1917": "In which year was the Russian Revolution?",
    "1976": "In which year did Concorde make its maiden commercial flight?",
    "Epistaxis": "What is the medical term for a nosebleed?",
    "What is the medical term for a nosebleed?": "Epistaxis",
    "Swim the Channel": "Captain Matthew Webb was the first person to do what?",
    "Captain Matthew Webb was the first person to do what?": "Swim the Channel",
    "Oxford": "What is the oldest University in Britain?",
    "What is the oldest University in Britain?": "Oxford",
    "Walt Disney": "Which person has won the most Oscars?",
    "Which person has won the most Oscars?": "Walt Disney",
    "Sodium Chloride": "What is the chemical name for table salt?",
    "What is the chemical name for table salt?": "Sodium Chloride",
    "Horses": "Hippophobia is the fear of which creatures?",
    "Hippophobia is the fear of which creatures?": "Horses",
    "Columbia": "What name was given to the original Space Shuttle?",
    "What name was given to the original Space Shuttle?": "Columbia",
    "Thomas Edison": "Who said \"Genius is 1% inspiration and 99% perspiration\"?",
    "Who said \"Genius is 1% inspiration and 99% perspiration\"?": "Thomas Edison",
    "William Shakespeare": "Which writer lived from 1564-1616?",
    "Which writer lived from 1564-1616?": "William Shakespeare",
    "Hindenburg": "Which airship infamously exploded over New Jersey in 1937?",
    "Which airship infamously exploded over New Jersey in 1937?": "Hindenburg",
    "Toyota Corolla": "What is the biggest selling car of all time?",
    "What is the biggest selling car of all time?": "Toyota Corolla",
    "All Shook Up": "What was the first UK No1 single for Elvis Presley?",
    "What was the first UK No1 single for Elvis Presley?": "All Shook Up",
    "One": "How many time zones are there in China?",
    "How many time zones are there in China?": "One",
    "How many spots are there on a pair of dice?": "42",
    "Preston": "The first stretch of motorway in Britain bypassed which town?",
    "The first stretch of motorway in Britain bypassed which town?": "Preston",
    "Origami": "The art of paper folding is known correctly as what?",
    "The art of paper folding is known correctly as what?": "Origami",
    "Shannon": "What is the longest river in the British Isles?",
    "What is the longest river in the British Isles?": "Shannon",
    "Mrs Hudson": "What was the name of Sherlock Holmes' housekeeper?",
    "What was the name of Sherlock Holmes' housekeeper?": "Mrs Hudson",
    "Elizabeth II": "Who is Britain longest reigning Monarch?",
    "Who is Britain longest reigning Monarch?": "Elizabeth II",
    "Threadneedle Street": "On what street is the Bank of England?",
    "On what street is the Bank of England?": "Threadneedle Street",
    "Buzz Aldrin": "Who was the 2nd man to step foot on the Moon?",
    "Who was the 2nd man to step foot on the Moon?": "Buzz Aldrin",
    "Tony Blackburn": "Who was the first ever DJ on Radio 1?",
    "Who was the first ever DJ on Radio 1?": "Tony Blackburn",
    "Methuselah": "Who was the oldest man in the Bible?",
    "Who was the oldest man in the Bible?": "Methuselah",
    "Nepal": "Kathmandu is the capital of which country?",
    "Which country has the worlds only non-rectangular flag?": "Nepal",
    "Buffalo": "Mozzarella cheese is made from which animal?",
    "Mozzarella cheese is made from which animal?": "Buffalo",
    "Sydney Opera House": "Jorn Utzon designed which famous building?",
    "Jorn Utzon designed which famous building?": "Sydney Opera House",
    "Kathmandu is the capital of which country?": "Nepal",
    "Belgium": "Sabena was the national airline of which country?",
    "Sabena was the national airline of which country?": "Belgium",
    "Read Only Memory": "In computing what does ROM stand for?",
    "In computing what does ROM stand for?": "Read Only Memory",
    "Battle of the Somme": "Tanks were first used in which Battle?",
    "Tanks were first used in which Battle?": "Battle of the Somme",
    "In what year did the Titanic sink?": "1912",
    "James I": "Which King was the target of the Gunpowder Plot?",
    "Which King was the target of the Gunpowder Plot?": "James I",
    "Dutch": "WWI spy Mata Hari was what nationality?",
    "WWI spy Mata Hari was what nationality?": "Dutch",
    "Turkey": "The Tulip originated in which modern day country?",
    "The Tulip originated in which modern day country?": "Turkey",
    "Mesopotamia": "Which ancient region translates as 'Land Between Two Rivers'?",
    "Which ancient region translates as 'Land Between Two Rivers'?": "Mesopotamia",
    "Grapefruit Orange Tangerine": "The Ugli fruit is a cross between which 3 fruits? List in alphabetical order.",
    "The Ugli fruit is a cross between which 3 fruits? List in alphabetical order.": "Grapefruit Orange Tangerine",
    "In what year was the first FA Cup Final?": "1872",
    "Crocus": "From which Flower is the spice Saffron obtained?",
    "From which Flower is the spice Saffron obtained?": "Crocus",
    "Ireland (Eire) and Denmark": "Which two countries joined the EEC at the same time as the UK?",
    "Which two countries joined the EEC at the same time as the UK?": "Ireland (Eire) and Denmark",
    "Palindrome": "What name is given to a word that reads the same forwards and backwards?",
    "What name is given to a word that reads the same forwards and backwards?": "Palindrome",
    "Linseed Oil": "What type of oil is used to strengthen cricket bats?",
    "What type of oil is used to strengthen cricket bats?": "Linseed Oil",
    "Foxglove": "From which flower is the drug Digitalis obtained?",
    "From which flower is the drug Digitalis obtained?": "Foxglove",
    "Royal Flush": "What is the highest hand in a game of Poker?",
    "What is the highest hand in a game of Poker?": "Royal Flush",
    "Ancient Cave Paintings": "Lascaux in Southern France is most famously known for what?",
    "Lascaux in Southern France is most famously known for what?": "Ancient Cave Paintings",
    "Crystal": "What is the traditional gift given on a 15th anniversary?",
    "What is the traditional gift given on a 15th anniversary?": "Crystal",
    "Mars": "Who was the Roman God of War?",
    "Who was the Roman God of War?": "Mars",
    "Machu Picchu": "Which ancient city was discovered by Hirham Bingham?",
    "Which ancient city was discovered by Hirham Bingham?": "Machu Picchu",
    "Pompeii and Herculaneum": "Which two cities were destroyed by Vesuvius in AD79?",
    "Which two cities were destroyed by Vesuvius in AD79?": "Pompeii and Herculaneum",
    "Legume": "A peanut is not a nut at all what type of food is it?",
    "A peanut is not a nut at all what type of food is it?": "Legume",
    "Acme": "Which company featured in the Wile E Coyote and Roadrunner cartoons?",
    "Which company featured in the Wile E Coyote and Roadrunner cartoons?": "Acme",
    "Abraham Lincoln": "Who was the 16th President of the USA?",
    "Who was the 16th President of the USA?": "Abraham Lincoln",
    "Alec Issigonis": "Who designed the Mini car?",
    "Who designed the Mini car?": "Alec Issigonis",
    "Proxima Centauri": "Apart from the Sun what is the nearest star to Earth?",
    "Apart from the Sun what is the nearest star to Earth?": "Proxima Centauri",
    "Robert Walpole": "Who was Britain's first Prime Minster?",
    "Who was Britain's first Prime Minster?": "Robert Walpole",
    "In which year was the Russian Revolution?": "1917",
    "Oberammergau": "Where does the famous Passion Play take place in Germany every 10 Years?",
    "Where does the famous Passion Play take place in Germany every 10 Years?": "Oberammergau",
    "Mario Puzo": "Who wrote the book The Godfather?",
    "Who wrote the book The Godfather?": "Mario Puzo",
    "Hungary": "Bulls Blood Wine is from which country?",
    "Bulls Blood Wine is from which country?": "Hungary",
    "Gin": "Juniper is a key ingredient of which spirit?",
    "Juniper is a key ingredient of which spirit?": "Gin",
    "Gustav Holst": "Who composed the Planet Suite?",
    "Who composed the Planet Suite?": "Gustav Holst",
    "Charlie Parker": "Which jazz musician was nicknamed 'Bird'?",
    "Which jazz musician was nicknamed 'Bird'?": "Charlie Parker",
    "How many bones are there in the adult human body?": "206",
    "The Simpsons": "In which TV show does Santa's Little Helper appear?",
    "In which TV show does Santa's Little Helper appear?": "The Simpsons",
    "Crash": "What is the collective noun for a group of Rhino?",
    "What is the collective noun for a group of Rhino?": "Crash",
    "Santa Maria": "What is the name of Christopher Columbus' Flagship?",
    "What is the name of Christopher Columbus' Flagship?": "Santa Maria",
    "Friend": "The Australian slang word 'Cobber' is translated as what in English?",
    "The Australian slang word 'Cobber' is translated as what in English?": "Friend",
    "North by Northwest": "Which Alfred Hitchcock movie ends with a scene on Mount Rushmore?",
    "Which Alfred Hitchcock movie ends with a scene on Mount Rushmore?": "North by Northwest",
    "Andorra": "Which tiny country is found nestled between France and Spain?",
    "Which tiny country is found nestled between France and Spain?": "Andorra",
    "Eminem": "Which musician's real name is Marshal Mathers?",
    "Which musician's real name is Marshal Mathers?": "Eminem",
    "Van Gogh": "Which artist painted Sun Flowers?",
    "Which artist painted Sun Flowers?": "Van Gogh",
    "Humphry Davy": "Who invented the Miners safety lamp and discovered the chemical element Sodium?",
    "Who invented the Miners safety lamp and discovered the chemical element Sodium?": "Humphry Davy",
    "How many Bits are there in a Byte?": "8",
    "Pink Floyd": "Which band had a famous album cover featuring Battersea Power Station?",
    "Which band had a famous album cover featuring Battersea Power Station?": "Pink Floyd",
    "In the Ear": "In which part of the body is the Stirrup Bone?",
    "In which part of the body is the Stirrup Bone?": "In the Ear",
    "Denali": "What is the highest mountain in the USA?",
    "What is the highest mountain in the USA?": "Denali",
    "Shakespearean Characters": "All but two of the moons of Uranus are named after what?",
    "All but two of the moons of Uranus are named after what?": "Shakespearean Characters",
    "How many pieces make up a Domino set?": "28",
    "Teddy Bears": "The Company 'Steiff' famously make what?",
    "The Company 'Steiff' famously make what?": "Teddy Bears",
    "Tin Lizzie": "What was the popular nickname for the Model T Ford?",
    "What was the popular nickname for the Model T Ford?": "Tin Lizzie",
    "Fred and Rose West": "Who infamously lived at 25 Cromwell Street, Gloucester?",
    "Who infamously lived at 25 Cromwell Street, Gloucester?": "Fred and Rose West",
    "Casino Royale": "What was the first James Bond novel?",
    "What was the first James Bond novel?": "Casino Royale",
    "Michael Fagan": "Who broke into the Queen's bedroom in 1982?",
    "Who broke into the Queen's bedroom in 1982?": "Michael Fagan",
    "Edwin Land": "Who invented the Polaroid camera?",
    "Who invented the Polaroid camera?": "Edwin Land",
    "Who Dares Wins": "What is the motto of the SAS?",
    "What is the motto of the SAS?": "Who Dares Wins",
    "Guinness": "Which alcoholic drink once advertised itself as 'Being Good for You'?",
    "Which alcoholic drink once advertised itself as 'Being Good for You'?": "Guinness",
    "Doric Ionic and Corinthian": "What are the three main types of Greek architecture?",
    "What are the three main types of Greek architecture?": "Doric Ionic and Corinthian",
    "Lumiere": "Which French brothers' are credited with early developments in film and photography?",
    "Which French brothers' are credited with early developments in film and photography?": "Lumiere",
    "Carousel": "The song 'You'll Never Walk Alone' comes from which musical?",
    "The song 'You'll Never Walk Alone' comes from which musical?": "Carousel",
    "Jane": "What is the first name of Agatha Christie's detective Miss Marple?",
    "What is the first name of Agatha Christie's detective Miss Marple?": "Jane",
    "Mahogany": "What type of wood did Thomas Chippendale mostly work with?",
    "What type of wood did Thomas Chippendale mostly work with?": "Mahogany",
    "Pressure": "An Isobar on a weather map links places with equal what?",
    "An Isobar on a weather map links places with equal what?": "Pressure",
    "Halleys Comet is visible from Earth in a cycle of how many years?": "76",
    "Regents": "London Zoo is situated in which park?",
    "London Zoo is situated in which park?": "Regents",
    "Roger Bannister": "Who was the first man to break the four minute mile?",
    "Who was the first man to break the four minute mile?": "Roger Bannister",
    "In which year did Concorde make its maiden commercial flight?": "1976",
    "Rosh Hashanah": "What is the Jewish Festival of New Year called?",
    "What is the Jewish Festival of New Year called?": "Rosh Hashanah",
    "Shintoism": "What is the national religion of Japan?",
    "What is the national religion of Japan?": "Shintoism",
    "Enola Gay": "What was the name of the aircraft which dropped the atom bomb on Hiroshima?",
    "What was the name of the aircraft which dropped the atom bomb on Hiroshima?": "Enola Gay",
    "Rio de Janeiro": "The statue of Christ the Redeemer overlooks which city?",
    "The statue of Christ the Redeemer overlooks which city?": "Rio de Janeiro",
    "The Farthing": "Which coin went out of circulation in 1960?",
    "Which coin went out of circulation in 1960?": "The Farthing"
},
    "331324" :   { "180": "angles of triangle add up to",
    "360": "angles of quadrilateral add up to",
    "540": "angles of pentagon add up to",
    "720": "angles of hexagon add up to",
    "rational numbers": "can be expressed in the form p/q",
    "can be expressed in the form p/q": "rational numbers",
    "Irrational numbers": "cannot be expressed as p/q. e.g. surds",
    "cannot be expressed as p/q. e.g. surds": "Irrational numbers",
    "y=mx+c": "form of a linear graph equation",
    "form of a linear graph equation": "y=mx+c",
    "Positive Gradient": "increase in y / increase in x",
    "increase in y / increase in x": "Positive Gradient",
    "negative gradient": "- y/x",
    "- y/x": "negative gradient",
    "standard index form": "A x 10 n",
    "A x 10 n": "standard index form",
    "Even number": "2x",
    "2x": "Even number",
    "Odd number": "2x + 1",
    "2x + 1": "Odd number",
    "mean": "total freq x values / total freq",
    "total freq x values / total freq": "mean",
    "lower quartile": "1/4(x+1)",
    "1/4(x+1)": "lower quartile",
    "Upper quartile": "3/4(x+1)",
    "3/4(x+1)": "Upper quartile",
    "upper bound": "cumulitive frequency is plotted at the ",
    "cumulitive frequency is plotted at the ": "upper bound",
    "frequency": "In a histogram the area of the bar represents the",
    "In a histogram the area of the bar represents the": "frequency",
    "Frequency density": "frequency / class width",
    "frequency / class width": "Frequency density",
    "relative probability": "times event happens / total No. of trials",
    "times event happens / total No. of trials": "relative probability",
    "1/2 x base x perpendicular height": "area of a triangle",
    "area of a triangle": "1/2 ac SinB",
    "1/2 (a+b) x perpendicular height": "area of a trapezium",
    "area of a trapezium": "1/2 (a+b) x perpendicular height",
    "length x perpendicular height": "area of a parallelogram",
    "area of a parallelogram": "length x perpendicular height",
    "pi x diameter": "circumference",
    "circumference": "pi x diameter",
    "pi x radius squared": "Area",
    "Area": "pi x radius squared",
    "indirect proportion": "xy=k",
    "xy=k": "indirect proportion",
    "direct proportion": "y=kx",
    "y=kx": "direct proportion",
    "area of cross-section x length": "area of a prism",
    "area of a prism": "area of cross-section x length",
    "2 x pi x radius": "circumference ",
    "circumference ": "2 x pi x radius",
    "angles of triangle add up to": "180",
    "angles of quadrilateral add up to": "360",
    "angles of pentagon add up to": "540",
    "angles of hexagon add up to": "720",
    "(n-2) x 180": "sum of angles",
    "sum of angles": "(n-2) x 180",
    "a2+b2=c2": "pythagoras' theorem",
    "pythagoras' theorem": "a2+b2=c2",
    "Sin x": "opp/hyp",
    "opp/hyp": "Sin x",
    "Cos x": "adj/hyp",
    "adj/hyp": "Cos x",
    "Tan x": "opp/adj",
    "opp/adj": "Tan x",
    "ax3 + bx2 + cx + d": "Cubic function",
    "Cubic function": "ax3 + bx2 + cx + d",
    "1/x": "reciprocal function",
    "reciprocal function": "1/x",
    "1 = 90 degrees": "Sin x circular function",
    "Sin x circular function": "1 = 90 degrees",
    "0 = 90 degrees": "Cos x circular function",
    "Cos x circular function": "0 = 90 degrees",
    "y = x power": "exponential function",
    "exponential function": "y = x power",
    "Sine rule": "a/Sin A = b/Sin B = c/Sin C",
    "a/Sin A = b/Sin B = c/Sin C": "Sine rule",
    "a2 = b2 + c2 - 2bc cosA": "Cosine rule- a",
    "Cosine rule- a": "a2 = b2 + c2 - 2bc cosA",
    "b2 = a2 + c2 -2ac cosB": "Cosine rule-b ",
    "Cosine rule-b ": "b2 = a2 + c2 -2ac cosB",
    "c2 = a2 + b2 -2ab CosC": "Cosine rule- c",
    "Cosine rule- c": "c2 = a2 + b2 -2ab CosC",
    "1/2 ac SinB": "area of a triangle" 
},
};
